import type { Problem, AnalyticsData, AdvancedAnalytics } from '../types';

export const mockProblems: Problem[] = [
  {
    id: '1',
    title: 'Two Sum',
    platform: 'LeetCode',
    difficulty: 'easy',
    topic: 'Arrays',
    timeSpent: 15,
    outcome: 'solved',
    date: 'Today',
    link: 'https://leetcode.com/problems/two-sum/',
    tags: ['Array', 'Hash Table', 'Two Pointers'],
    isRevision: false,
  },
  {
    id: '2',
    title: 'Longest Substring Without Repeating Characters',
    platform: 'LeetCode',
    difficulty: 'medium',
    topic: 'Strings',
    timeSpent: 45,
    outcome: 'hints',
    date: 'Yesterday',
    link: 'https://leetcode.com/problems/longest-substring-without-repeating-characters/',
    tags: ['String', 'Sliding Window', 'Hash Map'],
    isRevision: false,
  },
  {
    id: '3',
    title: 'Regular Expression Matching',
    platform: 'LeetCode',
    difficulty: 'hard',
    topic: 'Dynamic Programming',
    timeSpent: 90,
    outcome: 'failed',
    date: '2 days ago',
    link: 'https://leetcode.com/problems/regular-expression-matching/',
    tags: ['DP', 'Recursion', 'String'],
    isRevision: false,
  },
  {
    id: '4',
    title: 'Maximum Subarray',
    platform: 'LeetCode',
    difficulty: 'medium',
    topic: 'Arrays',
    timeSpent: 25,
    outcome: 'solved',
    date: '3 days ago',
    tags: ['Array', "Kadane's Algorithm", 'DP'],
    isRevision: false,
  },
  {
    id: '5',
    title: 'Valid Parentheses',
    platform: 'LeetCode',
    difficulty: 'easy',
    topic: 'Stack',
    timeSpent: 12,
    outcome: 'solved',
    date: '4 days ago',
    tags: ['Stack', 'String'],
    isRevision: false,
  },
  {
    id: '6',
    title: 'Merge Two Sorted Lists',
    platform: 'LeetCode',
    difficulty: 'easy',
    topic: 'Linked List',
    timeSpent: 18,
    outcome: 'solved',
    date: '5 days ago',
    tags: ['Linked List', 'Recursion'],
    isRevision: false,
  },
];

export const mockAnalytics: AnalyticsData = {
  totalProblems: 142,
  weeklySolved: 7,
  currentStreak: 23,
  successRate: 68,
  monthlyChange: 12,
  weeklyChange: 2,
  streakChange: 1,
  rateChange: 5,
};

export const mockAdvancedAnalytics: AdvancedAnalytics = {
  overview: {
    totalProblems: 247,
    totalLearningHours: 89.5,
    currentStreak: 23,
    successRate: 72,
    averageTimePerProblem: 28,
    totalTopics: 12,
    completedRoadmaps: 2,
  },
  performanceMetrics: {
    dailyActivity: [
      { date: '2024-01-15', problemsSolved: 3, learningHours: 2.5 },
      { date: '2024-01-14', problemsSolved: 2, learningHours: 1.8 },
      { date: '2024-01-13', problemsSolved: 4, learningHours: 3.2 },
      { date: '2024-01-12', problemsSolved: 1, learningHours: 0.5 },
      { date: '2024-01-11', problemsSolved: 3, learningHours: 2.1 },
      { date: '2024-01-10', problemsSolved: 2, learningHours: 1.9 },
      { date: '2024-01-09', problemsSolved: 5, learningHours: 4.1 },
    ],
    weeklyProgress: [
      { week: 'Week 1', problemsSolved: 18, successRate: 65 },
      { week: 'Week 2', problemsSolved: 22, successRate: 68 },
      { week: 'Week 3', problemsSolved: 25, successRate: 72 },
      { week: 'Week 4', problemsSolved: 28, successRate: 75 },
    ],
    monthlyTrends: [
      { month: 'Oct 2023', totalProblems: 45, averageTime: 32 },
      { month: 'Nov 2023', totalProblems: 52, averageTime: 29 },
      { month: 'Dec 2023', totalProblems: 48, averageTime: 26 },
      { month: 'Jan 2024', totalProblems: 62, averageTime: 24 },
    ],
  },
  topicAnalysis: {
    strongestTopics: [
      { topic: 'Arrays', successRate: 85, problemsSolved: 45 },
      { topic: 'Strings', successRate: 78, problemsSolved: 32 },
      { topic: 'Linked Lists', successRate: 72, problemsSolved: 28 },
    ],
    weakestTopics: [
      { topic: 'Dynamic Programming', successRate: 35, problemsSolved: 12 },
      { topic: 'Graphs', successRate: 42, problemsSolved: 18 },
      { topic: 'Tries', successRate: 38, problemsSolved: 8 },
    ],
    topicDistribution: [
      { topic: 'Arrays', count: 45, percentage: 18.2 },
      { topic: 'Strings', count: 32, percentage: 13.0 },
      { topic: 'Linked Lists', count: 28, percentage: 11.3 },
      { topic: 'Trees', count: 25, percentage: 10.1 },
      { topic: 'Dynamic Programming', count: 12, percentage: 4.9 },
      { topic: 'Graphs', count: 18, percentage: 7.3 },
      { topic: 'Others', count: 95, percentage: 38.5 },
    ],
  },
  difficultyAnalysis: {
    easyProblems: { solved: 89, total: 95, successRate: 94 },
    mediumProblems: { solved: 98, total: 125, successRate: 78 },
    hardProblems: { solved: 27, total: 45, successRate: 60 },
  },
  timeAnalysis: {
    bestPerformingHours: [
      { hour: 9, successRate: 85, problemsSolved: 12 },
      { hour: 14, successRate: 82, problemsSolved: 15 },
      { hour: 20, successRate: 78, problemsSolved: 18 },
      { hour: 10, successRate: 75, problemsSolved: 8 },
    ],
    averageTimeByDifficulty: {
      easy: 15,
      medium: 35,
      hard: 65,
    },
    productivityPatterns: [
      { day: 'Monday', productivity: 85 },
      { day: 'Tuesday', productivity: 92 },
      { day: 'Wednesday', productivity: 78 },
      { day: 'Thursday', productivity: 88 },
      { day: 'Friday', productivity: 82 },
      { day: 'Saturday', productivity: 95 },
      { day: 'Sunday', productivity: 70 },
    ],
  },
  aiInsights: {
    recommendations: [
      {
        type: 'topic',
        title: 'Focus on Dynamic Programming',
        description: 'Your DP success rate is 35% - significantly below average. Consider dedicating 2-3 hours weekly to DP fundamentals.',
        priority: 'high',
      },
      {
        type: 'time',
        title: 'Optimize Your Study Schedule',
        description: 'You perform best at 9 AM and 2 PM. Consider scheduling your most challenging problems during these hours.',
        priority: 'medium',
      },
      {
        type: 'pattern',
        title: 'Weekend Productivity Boost',
        description: 'Your productivity peaks on Saturdays (95%). Use weekends for tackling harder problems and learning new concepts.',
        priority: 'medium',
      },
    ],
    predictions: [
      { metric: 'Problems Solved', current: 247, predicted: 320, timeframe: 'Next Month' },
      { metric: 'Success Rate', current: 72, predicted: 78, timeframe: 'Next 2 Weeks' },
      { metric: 'Learning Hours', current: 89.5, predicted: 120, timeframe: 'Next Month' },
    ],
    strengths: [
      { area: 'Array Problems', description: 'Excellent performance with 85% success rate on array-based problems', confidence: 92 },
      { area: 'Consistent Practice', description: 'Maintained 23-day streak with regular problem-solving', confidence: 88 },
      { area: 'Time Management', description: 'Average solving time decreased by 25% over the last month', confidence: 85 },
    ],
    improvements: [
      { area: 'Dynamic Programming', description: 'Low success rate in DP problems', action: 'Start with basic DP patterns and work through LeetCode DP collection' },
      { area: 'Graph Algorithms', description: 'Struggling with graph traversal and shortest path problems', action: 'Practice BFS/DFS fundamentals and implement common graph algorithms' },
      { area: 'Hard Problems', description: 'Only 60% success rate on hard problems', action: 'Break down hard problems into smaller components and practice pattern recognition' },
    ],
  },
  learningProgress: {
    coursesCompleted: 3,
    coursesInProgress: 2,
    totalLearningHours: 89.5,
    learningStreak: 15,
    favoriteTopics: [
      { topic: 'Data Structures', hours: 25.5 },
      { topic: 'Algorithms', hours: 22.3 },
      { topic: 'System Design', hours: 18.7 },
      { topic: 'React Development', hours: 15.2 },
    ],
  },
  roadmapProgress: {
    totalRoadmaps: 4,
    completedRoadmaps: 2,
    inProgressRoadmaps: 2,
    nextMilestones: [
      { roadmap: 'Frontend Development', milestone: 'Complete React Advanced Concepts', progress: 75 },
      { roadmap: 'Data Structures & Algorithms', milestone: 'Master Dynamic Programming', progress: 30 },
      { roadmap: 'System Design', milestone: 'Design a Distributed System', progress: 45 },
    ],
  },
};